import streamlit as st
from PIL import Image
import cv2
import numpy as np
import time

# -----------------------------
# PAGE CONFIG
# -----------------------------
st.set_page_config(
    page_title="MediVision ",
    page_icon="🩺",
    layout="wide"
)

# -----------------------------
# LOAD CSS
# -----------------------------
with open("style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)

# -----------------------------
# FUNCTIONS
# -----------------------------
def preprocess_image(image):
    img = np.array(image)

    if len(img.shape) == 3:
        gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
    else:
        gray = img

    resized = cv2.resize(gray, (224, 224))
    return resized


def create_heatmap(image):
    img = np.array(image)

    if len(img.shape) == 2:
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)

    img = cv2.resize(img, (300, 300))
    heatmap = cv2.applyColorMap(img, cv2.COLORMAP_JET)
    heatmap = cv2.cvtColor(heatmap, cv2.COLOR_BGR2RGB)
    return heatmap


def generate_report(module, severity, confidence):
    report = f"""
MediVision Medical Report
----------------------------
Module: {module}
Severity Score: {severity}
Confidence: {confidence}%

Generated by MediVision 
"""
    return report

# -----------------------------
# SIDEBAR
# -----------------------------
st.sidebar.markdown("# 🩺 MediVision ")
st.sidebar.markdown("### Smart Diagnostics")
st.sidebar.markdown("---")

if "page" not in st.session_state:
    st.session_state.page = "Home"

if st.sidebar.button("🏠 Home"):
    st.session_state.page = "Home"

if st.sidebar.button("🫁 Chest X-ray"):
    st.session_state.page = "Chest"

if st.sidebar.button("🧠 Brain MRI"):
    st.session_state.page = "MRI"

if st.sidebar.button("🧴 Skin Analyzer"):
    st.session_state.page = "Skin"

if st.sidebar.button("ℹ About"):
    st.session_state.page = "About"

page = st.session_state.page

# -----------------------------
# HOME
# -----------------------------
if page == "Home":
    st.markdown("# Welcome to MediVision ")
    st.markdown("""
### AI-powered medical imaging platform for smarter diagnostics and early disease detection.
""")

    st.info("Upload medical images and receive AI-assisted diagnostic analysis in seconds.")

    col1, col2, col3 = st.columns(3)

    with col1:
        st.markdown("""
<div class='card'>
<h3>🫁 Chest X-ray</h3>
Detect pneumonia and lung diseases.
</div>
""", unsafe_allow_html=True)

    with col2:
        st.markdown("""
<div class='card'>
<h3>🧠 Brain MRI</h3>
Detect tumors and brain abnormalities.
</div>
""", unsafe_allow_html=True)

    with col3:
        st.markdown("""
<div class='card'>
<h3>🧴 Skin Analyzer</h3>
Analyze melanoma and skin disorders.
</div>
""", unsafe_allow_html=True)

# -----------------------------
# CHEST
# -----------------------------
elif page == "Chest":
    st.markdown("# 🫁 Chest X-ray Analyzer")

    uploaded = st.file_uploader("Upload Chest X-ray", type=["jpg", "png", "jpeg"])

    if uploaded:
        image = Image.open(uploaded)

        col1, col2 = st.columns(2)

        with col1:
            st.markdown("### Original Image")
            st.image(image, width=350)

        processed = preprocess_image(image)

        with col2:
            st.markdown("### Processed Image")
            st.image(processed, width=350)

        if st.button("Analyze"):
            with st.spinner("AI analyzing..."):
                time.sleep(2)

            severity = 87
            confidence = 94

            st.markdown("## Analysis Dashboard")
            st.progress(severity)

            if severity >= 80:
                st.error("🔴 Critical Risk: Pneumonia Detected")
            elif severity >= 60:
                st.warning("🟠 High Risk")
            elif severity >= 30:
                st.warning("🟡 Moderate Risk")
            else:
                st.success("🟢 Low Risk")

            st.metric("Confidence", f"{confidence}%")

            heatmap = create_heatmap(image)
            st.markdown("### AI Heatmap")
            st.image(heatmap, width=400)

            st.info("Recommendation: Consult pulmonologist.")

            report = generate_report("Chest X-ray", severity, confidence)

            st.download_button(
                "Download Report",
                report,
                file_name="medical_report.txt"
            )

# -----------------------------
# MRI
# -----------------------------
elif page == "MRI":
    st.markdown("# 🧠 Brain MRI Analyzer")
    uploaded = st.file_uploader("Upload MRI", type=["jpg","png","jpeg"])

    if uploaded:
        image = Image.open(uploaded)
        st.image(image, width=400)

        if st.button("Analyze MRI"):
            st.warning("⚠ Possible Tumor Detected")
            st.metric("Confidence", "91%")
            st.info("Recommendation: Consult neurologist.")

# -----------------------------
# SKIN
# -----------------------------
elif page == "Skin":
    st.markdown("# 🧴 Skin Disease Analyzer")
    uploaded = st.file_uploader("Upload Skin Image", type=["jpg","png","jpeg"])

    if uploaded:
        image = Image.open(uploaded)
        st.image(image, width=400)

        if st.button("Analyze Skin"):
            st.warning("⚠ Moderate Melanoma Risk")
            st.metric("Confidence", "88%")
            st.info("Recommendation: Visit dermatologist.")

# -----------------------------
# ABOUT
# -----------------------------
elif page == "About":
    st.markdown("# About MediVision ")
    st.markdown("""
### Technologies
- Python
- Streamlit
- OpenCV
- NumPy
- Computer Vision
- AI Diagnostics

### Features
- Multi-disease analysis
- Image preprocessing
- Heatmap visualization
- AI medical report generation
""")